### ISSUE TITLE
Unable to find the socket transport "unix"

### ISSUE THREAD

**Issue by deven003** [shpasser/GaeSupportLumen#3]
I am getting following error when I am trying to run a query.

```
lumen.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Unable to find the socket transport "unix" - did you forget to enable it when you configured PHP?' in vendor/illuminate/database/Connectors/Connector.php:55
```

**Comment by deven003** [comment]
Fixed it by replacing MySqlConnector.php with this https://gist.github.com/gmergoil/5693102 as suggested in this blog post https://gae-php-tips.appspot.com/2013/10/22/getting-started-with-laravel-on-php-for-app-engine/

**Comment by shpasser** [comment]
The original version of `MySqlConnector.php` should work Ok. I tested it several times with my other package https://github.com/shpasser/GaeSupportL5. There must be something else, like a configuration option, that was not intact.

**Comment by tvup** [comment]
Got the same problem (although not with lumen) and a google search got me here.
It seems like you need to have `/cloudsql/ `in front of the connection name.
So your .env file would have an entry like this:
DB_SOCKET=/cloudsql/app-id:region:database-nameish-thing

**Comment by shpasser** [comment]
I think that as of now the following link should have the information on how to connect to CloudSQL instance from PHP https://cloud.google.com/appengine/docs/standard/php/cloud-sql/

**Comment by shpasser** [comment]
In general Google can change their socket connection string format whenever they want, meaning we have to understand the platforms we are working with.
